In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
documents = ["The cat sat on the mat",
            "The dog sat on the floor",
            "The cat and the dog played together"]

In [8]:
documents[0]

'The cat sat on the mat'

In [3]:
vectorizer = CountVectorizer()

In [4]:
vectorizer

,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None
,"stop_words stop_words: {'english'}, list, default=NoneIf 'english', a built-in stop word list for English is used.There are several known issues with 'english' and you shouldconsider an alternative (see :ref:`stop_words`).If a list, that list is assumed to contain stop words, all of whichwill be removed from the resulting tokens.Only applies if ``analyzer == 'word'``.If None, no stop words will be used. In this case, setting `max_df`to a higher value, such as in the range (0.7, 1.0), can automatically detectand filter stop words based on intra corpus document frequency of terms.",None
,"token_pattern token_pattern: str or None, default=r""(?u)\\b\\w\\w+\\b""Regular expression denoting what constitutes a ""token"", only usedif ``analyzer == 'word'``. The default regexp select tokens of 2or more alphanumeric characters (punctuation is completely ignoredand always treated as a token separator).If there is a capturing group in token_pattern then thecaptured group content, not the entire match, becomes the token.At most one capturing group is permitted.",'(?u)\\b\\w\\w+\\b'
,"ngram_range ngram_range: tuple (min_n, max_n), default=(1, 1)The lower and upper boundary of the range of n-values for differentword n-grams or char n-grams to be extracted. All values of n suchsuch that min_n <= n <= max_n will be used. For example an``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` meansunigrams and bigrams, and ``(2, 2)`` means only bigrams.Only applies if ``analyzer`` is not callable.","(1, ...)"
,"analyzer analyzer: {'word', 'char', 'char_wb'} or callable, default='word'Whether the feature should be made of word n-gram or charactern-grams.Option 'char_wb' creates character n-grams only from text insideword boundaries; n-grams at the edges of words are padded with space.If a callable is passed it is used to extract the sequence of featuresout of the raw, unprocessed input... versionchanged:: 0.21Since v0.21, if ``input`` is ``filename`` or ``file``, the data isfirst read from the file and then passed to the given callableanalyzer.",'word'


In [11]:
X = vectorizer.fit_transform(documents)

In [14]:
type(X)

scipy.sparse._csr.csr_matrix

In [15]:
X.toarray()

array([[0, 1, 0, 0, 1, 1, 0, 1, 2, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 2, 0],
       [1, 1, 1, 0, 0, 0, 1, 0, 2, 1]])

In [21]:
X_array = X.toarray()

In [16]:
feature_names = vectorizer.get_feature_names_out()

In [17]:
feature_names

array(['and', 'cat', 'dog', 'floor', 'mat', 'on', 'played', 'sat', 'the',
       'together'], dtype=object)

In [7]:
import pandas as pd

In [22]:
df = pd.DataFrame(X_array, columns=feature_names)
df

,and,cat,dog,floor,mat,on,played,sat,the,together
0,0,1,0,0,1,1,0,1,2,0
1,0,0,1,1,0,1,0,1,2,0
2,1,1,1,0,0,0,1,0,2,1


# BOW issue

In [1]:
sentences = [
    "The man bit the dog",
    "The dog bit the man"
]

In [5]:
X = vectorizer.fit_transform(sentences)
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (2, 4)>

In [6]:
X.toarray()

array([[1, 1, 1, 2],
       [1, 1, 1, 2]])

In [8]:
X_array = X.toarray()
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(X_array, columns=feature_names)
df

,bit,dog,man,the
0,1,1,1,2
1,1,1,1,2


In [9]:
# word2vec

In [14]:
import gensim

In [13]:
# pip install gensim

In [15]:
from gensim.models import Word2Vec

In [16]:
sentences = [
    "The cat sat on the mat",
    "The dog sat on the floor",
    "The cat and the dog played together"
]

In [17]:
tokenized_sentences = []
for sentence in sentences:
    tokenized_sentences.append(sentence.lower().split())

tokenized_sentences

[['the', 'cat', 'sat', 'on', 'the', 'mat'],
 ['the', 'dog', 'sat', 'on', 'the', 'floor'],
 ['the', 'cat', 'and', 'the', 'dog', 'played', 'together']]

In [32]:
model = Word2Vec(sentences = tokenized_sentences, vector_size=100, min_count=1)

In [33]:
model

In [34]:
cat_embedding = model.wv['cat']
cat_embedding

array([-0.00713902,  0.00124103, -0.00717672, -0.00224462,  0.0037193 ,
        0.00583312,  0.00119818,  0.00210273, -0.00411039,  0.00722533,
       -0.00630704,  0.00464722, -0.00821997,  0.00203647, -0.00497705,
       -0.00424769, -0.00310898,  0.00565521,  0.0057984 , -0.00497465,
        0.00077333, -0.00849578,  0.00780981,  0.00925729, -0.00274233,
        0.00080022,  0.00074665,  0.00547788, -0.00860608,  0.00058446,
        0.00686942,  0.00223159,  0.00112468, -0.00932216,  0.00848237,
       -0.00626413, -0.00299237,  0.00349379, -0.00077263,  0.00141129,
        0.00178199, -0.0068289 , -0.00972481,  0.00904058,  0.00619805,
       -0.00691293,  0.00340348,  0.00020606,  0.00475375, -0.00711994,
        0.00402695,  0.00434743,  0.00995737, -0.00447374, -0.00138926,
       -0.00731732, -0.00969783, -0.00908026, -0.00102275, -0.00650329,
        0.00484973, -0.00616403,  0.00251919,  0.00073944, -0.00339215,
       -0.00097922,  0.00997913,  0.00914589, -0.00446183,  0.00

In [37]:
similar = model.wv.most_similar('cat', topn=5)
similar

[('on', 0.17018885910511017),
 ('together', 0.13887983560562134),
 ('played', 0.03479551896452904),
 ('dog', 0.004503022879362106),
 ('the', -0.027750348672270775)]

In [38]:
similarity = model.wv.similarity('cat', 'dog')
similarity

np.float32(0.0045030187)